server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
#    password: tu_password_aqui
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: INFO